### ISSUE TITLE
USB 3.0 is working but USB 2.0 is not working

### ISSUE THREAD

**Issue by kk98** [mrpapersonic/hp-eb-9480m-oc-efi#2]
Hi, I have HP Folio 9480m and I have used your EFI folder to install the macOS BigSur using OpenCore boot loader. It was successfully installed and working but two USB ports on the right side which are 2.0, not working. Left side single USB port is working which is 3.0 

Please review my config.plsit , and screenshot of System Report.

Update: I have also successfully updated my macOS to Monterey (12.3.1), every thing is working same like before but still USB 2.0 is not working like before.

So, I am currently running macOS Monterey (12.3.1)
![Screenshot 2022-04-08 at 4 30 38 PM](https://user-images.githubusercontent.com/16766950/162427576-28f83d37-b800-4d42-b739-5ad84e635d36.png)
[config.plist.zip](https://github.com/mrpapersonic/hp-eb-9480m-oc-efi/files/8451425/config.plist.zip)

**Comment by mrpapersonic** [comment]
[USBMap.zip](https://github.com/mrpapersonic/hp-eb-9480m-oc-efi/files/8456440/USBMap.zip)
Please update USBMap.kext and USBMapLegacy.kext with these versions and restart.

For some reason, the two USB ports on the right were labelled USB 2.0 in USBMap.kext, when they are actually USB SuperSpeed (USB 3.0). This is fixed and the newer kexts.

**Comment by kk98** [comment]
Hi, Thanks for your prompt response.

I have updated the provided kext files in my EFI partition OC/Kext/ folder and restarted my MAC but still the same behaviour. USB is working on the USB 3.0 port (left sided single port), not working on the both right sided ports.

Should I have to reset NVRAM? I haven't reset it yet.

Update: I have reset the NVRAM, but still no effect still same behaviour. Attached is screenshot of system information.

![Screenshot 2022-04-09 at 2 07 01 PM](https://user-images.githubusercontent.com/16766950/162564909-bfb4c2ec-54cb-4f6f-a944-f84ae74c4a00.png)

**Comment by mrpapersonic** [comment]
Please try this pack. The Monterey update has screwed over my USB mappings.
[USBMap.zip](https://github.com/mrpapersonic/hp-eb-9480m-oc-efi/files/8457180/USBMap.zip)
 If this fails, use [USBInjectAll](https://bitbucket.org/RehabMan/os-x-usb-inject-all/downloads/).

**Comment by kk98** [comment]
Provided USBMap didn't worked. I have tried at my own using the OpenCore USB mapping guide and USB Map tool, and now my all ports all working. I am attaching my USBMap kext files check this out in case anyone needs it.

[USBMap.zip](https://github.com/mrpapersonic/hp-eb-9480m-oc-efi/files/8457793/USBMap.zip)
